version: '3.8'
services:
  client:
    build:
      context: ./client
    command:
      - ./script/dev
    volumes:
      - jsbuild:/usr/src/aud-it/.build
      - ./server/internal/schema/graphql:/usr/src/aud-it/src/graphql/schema

      - ./client:/usr/src/aud-it
      - ./server/internal/schema/graphql:/schema
  server:
    build:
      context: ./server
    command:
      - ./script/dev
    ports:
      - '4510:8080'
    volumes:
      - storage:/storage
      - jsbuild:/public

      - ./server:/go/src/github.com/bensaufley/aud-it
volumes:
  storage:
  jsbuild:
    
